name: Artifact
on: [push]

jobs:
  artifact:
    name: Compile and upload the pdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst setup
        uses: typst-community/setup-typst@v4
      - name: Compile
        run: typst compile rapport.typ
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: rapport
          path: rapport.pdf
